version: '3.7'

# create a .env file with rootpw and userpw
# else it defaults to toor and resu

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${rootpw:-toor}
      MYSQL_DATABASE: a02-shopsystem
      MYSQL_USER: user
      MYSQL_PASSWORD: ${userpw:-resu}
    ports:
      - 3312:3306
    volumes:
      - a02-shopsystem-mysql-data:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

volumes:
  a02-shopsystem-mysql-data:
