// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using a02_shopsystem.Model;

#nullable disable

namespace a02_shopsystem.Migrations
{
    [DbContext(typeof(ShopsystemContext))]
    [Migration("00initialCreate")]
    partial class _00initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");

            modelBuilder.Entity("a02_shopsystem.Model.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("EuroPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("euroPrice");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("shopId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Articles_name_idx");

                    b.HasIndex(new[] { "ShopId" }, "Articles_shopId_fk");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("a02_shopsystem.Model.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "Shops_name_idx");

                    b.ToTable("Shops", (string)null);
                });

            modelBuilder.Entity("a02_shopsystem.Model.Article", b =>
                {
                    b.HasOne("a02_shopsystem.Model.Shop", "Shop")
                        .WithMany("Articles")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Articles_shopId_fk");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("a02_shopsystem.Model.Shop", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
